Issue01 - Item Card Component
hack4impact-calpoly/wilshire-hope-chest pull request #10
Opened 2023-03-07 01:49 UTC by andrewtchan

## Developer: Andrew Chan

### Pull Request Summary

Submitting pull request for Issue 01 including ItemCard.tsx and ItemCard.css

### Pull Request Checklist

- [x] Code is neat, readable, and works
- [x] Comments are appropriate
- [x] The commit messages follows our [guidelines](https://h4i.notion.site/Conventional-Commits-593452ad1179489399ad3bd696ef772a)
- [x] The developer name is specified
- [x] The summary is completed
- [x] Ask for a review in communication channels

### Reviewer Checklist - PULL REQUEST REVIEWER ONLY

IMPORTANT: The rest of the sections in this checklist should only be filled out by authorized pull request reviewers. If you are the individual contributor, do not fill out the rest of the fields or check the boxes.

## Reviewer: Full Name

NOTE: Pull requests should only be merged when all boxes are checked.

- [ ] Assign yourself as reviewer if not assigned
- [ ] The reviewer name is specified
- [ ] The code is fully reviewed
- [ ] Meaningful feedback is given
- [ ] Let developer know a review has been made

2023-03-09 00:02 UTC, jlaksana commented
Please undo all the modifications to the other files that you didn't create. This is probably left over stuff from when we did setup

2023-03-09 03:10 UTC, andrewtchan commented
Reverted all changes to files besides ItemCard.tsx and ItemCard.css

2023-03-12 21:37 UTC, jlaksana requested changes

2023-03-12 23:15 UTC, andrewtchan commented on src/components/ItemCard.css
> +  position: absolute;
I think the absolutes for the nested divs within the item-card div are necessary for spacing within the ItemCard. I looked at the css documentation and I think just removing the positioning attributes from the top level class (like in my commit) does what you wanted, which is make the component track the top left. Let me know if that's still not correct.

2023-03-12 23:17 UTC, andrewtchan commented on src/components/ItemCard.tsx
> +          <div className="item-card-date">{date}</div>
I used mm/dd/yyyy formatting for this.

2023-03-13 00:49 UTC, jlaksana approved these changes
Thanks for making those changes!

2023-03-13 00:49 UTC, merged